### ISSUE TITLE
I open a png file and the output is this

### ISSUE THREAD

**Issue by aalmiramolla** [brad/Inkscape-OpenSCAD-DXF-Export#1]
`Traceback (most recent call last):
  File "openscad_dxf.py", line 231, in <module>
    if __name__ == '__main__': OpenSCADDXFEffect().affect()
  File "/usr/share/inkscape/extensions/inkex.py", line 221, in affect
    self.effect()
  File "openscad_dxf.py", line 199, in effect
    [self.global_dims['minX'], self.global_dims['maxX']])
  File "openscad_dxf.py", line 126, in dxf_add_dimension
    ('13', '%f' % (x[0] if x is not None else 0.0)),
TypeError: float argument required, not NoneType`

**Comment by aalmiramolla** [comment]
Whit svg works rare

**Comment by brad** [comment]
@aalmiramolla  The plugin is only meant for vector graphics, it is not intended to work with a png, unless you trace it first. Could you please provide an example of an SVG that it doesn't work with so I can debug it?

**Comment by brad** [comment]
No response for over 6 months closing. Please reopen if you want to discuss it more
