### ISSUE TITLE
can not install this plug-in now?

### ISSUE THREAD

**Issue by eexpress** [brad/Inkscape-OpenSCAD-DXF-Export#14]
> Package: inkscape
> Version: 0.91-7ubuntu2

simple copy files into $HOME/.config/inkscape/extensions
or
```
▶ pip install --target=$HOME/.config/inkscape/extensions inkscape-openscad-dxf
Collecting inkscape-openscad-dxf
  Downloading inkscape-openscad-dxf-0.0.3.tar.gz
Collecting setuptools (from inkscape-openscad-dxf)
  Downloading setuptools-33.1.1-py2.py3-none-any.whl (472kB)
    100% |████████████████████████████████| 481kB 64kB/s 
Building wheels for collected packages: inkscape-openscad-dxf
  Running setup.py bdist_wheel for inkscape-openscad-dxf ... done
  Stored in directory: /home/eexp/.cache/pip/wheels/14/88/5d/a68f327f3a88c201b9ede10065baae7e5a039bc8ba880b5506
Successfully built inkscape-openscad-dxf
Installing collected packages: setuptools, inkscape-openscad-dxf
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 335, in run
    prefix=options.prefix_path,
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 732, in install
    **kwargs
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 837, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 1039, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/usr/lib/python2.7/dist-packages/pip/locations.py", line 153, in distutils_scheme
    i.finalize_options()
  File "/usr/share/python-wheels/setuptools-20.7.0-py2.py3-none-any.whl/setuptools/command/install.py", line 38, in finalize_options
    orig.install.finalize_options(self)
  File "/usr/lib/python2.7/distutils/command/install.py", line 289, in finalize_options
    raise DistutilsOptionError("can't combine user with prefix, "
DistutilsOptionError: can't combine user with prefix, exec_prefix/home, or install_(plat)base
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

```

nothing appeared in the save as menu.

**Comment by brad** [comment]
@eexpress I'm sorry to say I can't reproduce the problem. It works for me on Inkscape 0.92. I'm not sure why it's not working with the manual install (file permissions? Are they readable? Is the directory executable?) but your pip install clearly shows an error that is not related to the code for this package.

**Comment by eexpress** [comment]
▶ tree ~/.config/inkscape/extensions
/home/eexp/.config/inkscape/extensions
├── openscad_dxf
│   ├── dxf_color.py
│   ├── \_\_init\_\_.py
│   ├── inkinkex.py
│   ├── inkutils.py
│   ├── object2path.py
│   └── openscad_dxf.py
└── openscad_dxf.inx

▶ ll openscad_dxf/
总用量 484
drwxrwxr-x 2 eexp eexp   4096 1月  18 11:11 ./
drwxr-x--x 3 eexp eexp   4096 1月  18 11:11 ../
-rwxrwxr-x 1 eexp eexp 122593 1月  18 11:10 dxf_color.py*
-rwxrwxr-x 1 eexp eexp  33764 1月  18 11:10 \_\_init\_\_.py*
-rwxrwxr-x 1 eexp eexp  78671 1月  18 11:10 inkinkex.py*
-rwxrwxr-x 1 eexp eexp  41122 1月  18 11:10 inkutils.py*
-rwxrwxr-x 1 eexp eexp  48079 1月  18 11:10 object2path.py*
-rwxrwxr-x 1 eexp eexp 124577 1月  18 11:10 openscad_dxf.py*

does this right?

**Comment by brad** [comment]
@eexpress Hmm, seems like that should work. Can you try opening inkscape from the command line and see if there are any errors output related to this extension?

**Comment by eexpress** [comment]
here is the output


[output-inkscape.txt](https://github.com/brad/Inkscape-OpenSCAD-DXF-Export/files/720912/output-inkscape.txt)

**Comment by brad** [comment]
@eexpress OK, I think the problem is you have the wrong data in `openscad_dxf.inx`. I'm guessing you did a File->Save on [this page](https://github.com/brad/Inkscape-OpenSCAD-DXF-Export/blob/master/openscad_dxf.inx). If you are saving files from the github website, you need to click the "Raw" button first.

**Comment by eexpress** [comment]
thanks, I got this. :(

**Comment by brad** [comment]
Great! Let me know if you have any other issues
